# Generated by Django 3.1.7 on 2021-04-09 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('quiz', '0002_testanswers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='wrong_answers',
        ),
        migrations.AddField(
            model_name='wronganswers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questions'),
        ),
        migrations.AlterField(
            model_name='test',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='users.student'),
        ),
    ]
