# Generated by Django 3.1.7 on 2021-04-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210409_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wronganswers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wrong_answers', to='quiz.questions'),
        ),
    ]
