# Generated by Django 3.1.7 on 2021-04-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('quiz', '0006_auto_20210409_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test', related_query_name='tests', to='users.student'),
        ),
        migrations.AlterField(
            model_name='testanswers',
            name='answer',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='testanswers',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.test'),
        ),
    ]
