# Generated by Django 3.1.7 on 2021-04-10 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('quiz', '0007_auto_20210410_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', related_query_name='tests', to='users.student'),
        ),
    ]
