# Generated by Django 3.1.7 on 2021-03-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.JSONField(default='test'),
            preserve_default=False,
        ),
    ]
