# Generated by Django 3.1.7 on 2021-03-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_student_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.JSONField(null=True),
        ),
    ]
