# Generated by Django 3.1.7 on 2021-03-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20210329_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
